# Generated by Django 3.1.6 on 2021-02-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('headline', models.CharField(max_length=200)),
                ('url_title', models.CharField(max_length=25)),
                ('content', models.TextField()),
                ('tag', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=35)),
            ],
        ),
    ]
